version: 2.1

defaults: &defaults
    docker:
        - image: circleci/node:10.13.0
    working_directory: ~/synthio

jobs:
    build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                key: yarn-cache-{{ checksum "~/synthio/theme/yarn.lock" }}

            - restore_cache:
                key: node-modules-{{ checksum "~/synthio/theme/yarn.lock" }}

            - run:
                name: Install Dependencies
                working_directory: ~/synthio/theme
                command: |
                    yarn install

            - save_cache:
                key: yarn-cache-{{ checksum "~/synthio/theme/yarn.lock" }}
                paths:
                    - ~/.cache/yarn

            - save_cache:
                key: node-modules-{{ checksum "~/synthio/theme/yarn.lock" }}
                paths:
                    - ~/synthio/theme/node_modules

            - run:
                name: Install Wordpress
                working_directory: ~/synthio/
                command: |
                    wget https://wordpress.org/latest.zip; unzip latest.zip; cd wordpress; cp -fR * ..; cd ..; rm -fR wordpress

            - run:
                name: Build
                working_directory: ~/synthio/theme
                command: |
                    yarn run build

            - run:
                name: Move things into place
                working_directory: ~/synthio
                command: |
                    rm -fR ./wp-content/themes/synthio2019
                    rm -fR ./wp-content/plugins
                    mv ./plugins ./wp-content/plugins
                    mv ./theme ./wp-content/themes/synthio2019


            - run:
                name: Update .gitignore files
                command: |
                    find `pwd` -name '.gitignore' -print0 | while IFS= read -r -d $'\0' file; do
                        echo $file
                        sed -i -e 's/# ::: //g' $file
                        sed -i -e '/.*::: cut :::*/,$d' $file
                    done

            - persist_to_workspace:
                root: ~/synthio
                paths: .

    deploy_production:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/synthio

            - add_ssh_keys:
                fingerprints:
                    - "ba:ca:75:29:c2:41:8f:70:bb:98:f3:16:03:00:b1:47"

            - deploy:
                command: |
                    echo -e "\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tHostName git.wpengine.com\n\tUser git" > ~/.ssh/config
                    git config --global user.email "george@hotsauceatl.com"
                    git config --global user.name "Hot Sauce [circleci]"
                    git clone git@git.wpengine.com:production/synthio tmp_remote
                    rm -rf .git
                    mv tmp_remote/.git .git
                    rm -rf tmp_remote
                    git add -A
                    git commit -m"deploy"
                    git push -o nolint origin master

    deploy_staging:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/synthio

            - add_ssh_keys:
                fingerprints:
                    - "ba:ca:75:29:c2:41:8f:70:bb:98:f3:16:03:00:b1:47"

            - deploy:
                command: |
                    echo -e "\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tHostName git.wpengine.com\n\tUser git" > ~/.ssh/config
                    git config --global user.email "george@hotsauceatl.com"
                    git config --global user.name "Hot Sauce [circleci]"
                    git clone git@git.wpengine.com:production/synthiostage tmp_remote
                    rm -rf .git
                    mv tmp_remote/.git .git
                    rm -rf tmp_remote
                    git add -A
                    git commit -m"deploy"
                    git push -o nolint origin master

    deploy_dev:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/synthio

            - add_ssh_keys:
                fingerprints:
                    - "ba:ca:75:29:c2:41:8f:70:bb:98:f3:16:03:00:b1:47"

            - deploy:
                command: |
                    echo -e "\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tHostName git.wpengine.com\n\tUser git" > ~/.ssh/config
                    git config --global user.email "george@hotsauceatl.com"
                    git config --global user.name "Hot Sauce [circleci]"
                    git clone git@git.wpengine.com:production/synthiodevelop tmp_remote
                    rm -rf .git
                    mv tmp_remote/.git .git
                    rm -rf tmp_remote
                    git add -A
                    git commit -m"deploy"
                    git push -o nolint origin master

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy_production:
                requires:
                    - build
                filters:
                    branches:
                        only: master
            - deploy_staging:
                requires:
                    - build
                filters:
                    branches:
                        only: /^release\/.*/
            - deploy_dev:
                requires:
                    - build
                filters:
                    branches:
                        only: develop